[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
uuid = { version = "^0.8", features = ["v4"] }
serde = { version = "1.0.197", features=["derive"] }
